### ISSUE TITLE
uvoz podatkov

### ISSUE THREAD

**Issue by nastja88** [nastja88/APPR-2017#1]
Imam težave z uvozom podatkov. Program mi vrne napako, da ne najde datoteke, čeprav imam pravilno nastavljen direktorij.

**Comment by jaanos** [comment]
Sklepam, da uporabljaš različico programa `uvoz.r`, ki jo imaš v veji `patch-1` - kot sem ti napisal v jaanos#5, raje commite delaj lokalno (pred tem seveda naredi pull, da dobiš aktualno različico iz GitHuba).

Najprej odstrani kodo iz vzorca, saj je ne potrebuješ več. V prvem svojem klicu potem bereš `uvoz.r` - to seveda ni datoteka CSV, tako da branje ne bo uspelo. Pri nadaljnjih branjih ne pozabi na končnice datotek - te so povsod `.csv`, tako da jih dodaj k imenom datotek.

Svetujem še, da za uvoz raje uporabiš funkcijo `read_csv2` iz knjižnice `readr`, kot smo to počeli na vajah (posodobil sem tudi [vzorec](https://github.com/jaanos/APPR-2017/blob/master/uvoz/uvoz.r)). V vsakem primeru pa pri uvozu navedi kodiranje znakov, da se bodo podatki pravilno uvozili na vseh sistemih. Kolikor vidim, tvoji podatki sicer nimajo posebnih znakov, tako da lahko uporabiš kar `UTF-8`.
